# Generated by Django 3.2.9 on 2021-12-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('main_img', models.ImageField(upload_to='')),
                ('desc1', models.CharField(max_length=300)),
                ('desc2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('info_descrption', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='region',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='service',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fly_from',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='images',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='region',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='FlyFrom',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
